# Generated by Django 5.1.6 on 2025-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(),
        ),
    ]
